-- Generated by tools/lines.py from the clips in Sounds/. Do not edit:
-- run a tool that writes clips, or python tools/lines.py, to refresh it.
local _, ns = ...
ns.COUNTS = {
    fire = 20,
    big_hit = 20,
    aggro = 20,
    aggro_close = 20,
    tank_lost = 20,
    cc = 20,
    boss_you = 20,
    boss_emote = 20,
    drowning = 20,
    fatigue = 20,
    death = 20,
    pull = 20,
    wipe = 20,
    kill = 20,
    durability = 20,
    ready_check = 20,
    range = 20,
}
